name: 'Upload Android Listings'
description: 'Upload Android Applications Title and Description to Google Play'
author: 'gregoirekourdouli'
branding:
  icon: 'truck'
  color: 'yellow'
inputs:
  serviceAccountJson:
    description: "The service account json private key file to authorize the upload request"
    required: false
  serviceAccountJsonPlainText:
    description: "The raw json text of the service account private key to authorize the upload request"
    required: false
  packageName:
    description: "Package name of the app"
    required: true
  language:
    description: "Language localization code (BCP-47 language tag)"
    required: true
  title:
    description: "File containing the localized title of the app"
    required: false
  fullDescription: 
    description: "File containing the full description of the app"
    required: false
  shortDescription: 
    description: "File containing the short description of the app"
    required: false
  video: 
    description: "File containing the URL of a promotional YouTube video for the app"
    required: false
  changesNotSentForReview:
    description: "Indicates that the changes in this edit will not be reviewed until they are explicitly sent for review from the Google Play Console"
    required: false
    default: 'false'
runs:
  using: 'node20'
  main: 'lib/index.js'
